export const AGENT_METADATA_REPOSITORY_TOKEN = Symbol('AGENT_METADATA_REPOSITORY');
export const AGENT_SESSION_MANAGER_TOKEN = Symbol('AGENT_SESSION_MANAGER');

export const AGENT_SERVICE_TOKEN = Symbol('AGENT_SERVICE');

export const AGENT_MANAGER_TOKEN = Symbol('AGENT_MANAGER');
