name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm -r lint
        continue-on-error: false

      - name: Build packages (libraries)
        run: pnpm --filter "./packages/*" build
        continue-on-error: false

      - name: Build apps
        run: pnpm --filter "./apps/*" build
        continue-on-error: false

      - name: Run type check
        run: pnpm -r typecheck
        continue-on-error: false

      - name: Run Vitest (non-watch, with coverage)
        run: pnpm -r test:vitest
        continue-on-error: false

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage/**

      - name: Upload to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/**/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Success
        run: echo "✅ CI passed successfully"
