name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm -r lint
        continue-on-error: false

      - name: Build packages (libraries)
        run: pnpm --filter "./packages/*" build
        continue-on-error: false

      - name: Build apps
        run: pnpm --filter "./apps/*" build
        continue-on-error: false

      - name: Run type check
        run: pnpm -r typecheck
        continue-on-error: false

      - name: Run tests
        run: pnpm -r --if-present test
        continue-on-error: false

      - name: Success
        run: echo "✅ CI passed successfully"
