name: Vitest (monorepo)

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run Vitest (no watch)
        env:
          CI: 'true'
        run: pnpm -r test:vitest

